package com.example

import androidx.compose.runtime.staticCompositionLocalOf

/** Kumpulan teks antarmuka untuk satu bahasa. */
data class Strings(
    // Header
    val appTitle: String,
    val appTitleAccent: String,
    val shizukuConnected: String,
    val shizukuDisconnected: String,
    val settings: String,
    // VPN card
    val vpnFilter: String,
    val vpnOff: String,
    val vpnOnActive: String,
    val vpnOnPreparing: String,
    // Memory card
    val memoryUsage: String,
    val memoryShort: String,
    val ramUsedLabel: String,
    val ramTotalLabel: String,
    val ramInUseLabel: String,
    val ramUserAppsLabel: String,
    val ramCacheLabel: String,
    val ramSystemLabel: String,
    val ramFreeLabel: String,
    // Quick actions
    val networkAccessAll: String,
    val killAll: String,
    val filterAndSort: String,
    // Tabs / titles
    val userApps: String,
    val systemApps: String,
    val info: String,
    val tabApps: String,
    val tabSystem: String,
    val tabAbout: String,
    // About
    val version: String,
    val serviceStatus: String,
    // Permission dialog
    val permissionsTitle: String,
    val permissionsSearch: String,
    val permissionsEmpty: String,
    val permissionsNoMatch: String,
    val permissionsRuntime: String,
    val permissionsAppOps: String,
    val legendChangeable: String,
    val legendLocked: String,
    val locked: String,
    val close: String,
    // Settings screen
    val settingsTitle: String,
    val languageSection: String,
    val themeSection: String,
    val themeDark: String,
    val themeLight: String,
    val themeSystem: String,
    val languageIndonesian: String,
    val languageEnglish: String,
    val openSystemAppInfo: String,
    val back: String,
    val generalSection: String,
    val otherSection: String,
    // Pencarian aplikasi
    val searchApps: String,
    val noMatchApps: String,
    val clearSearch: String,
    // Info aplikasi
    val appInfoTitle: String,
    val labelPackage: String,
    val labelUid: String,
    val labelVersion: String,
    val labelInstalled: String,
    val labelUpdated: String,
    val labelSdk: String,
    val labelType: String,
    val labelNetwork: String,
    val labelRunning: String,
    val typeUserApp: String,
    val typeSystemApp: String,
    val runningYes: String,
    val runningNo: String,
    val copyAction: String,
    val copiedAction: String,
    val systemInfoAction: String,
    val activeLabel: String,
    // Mode minimalis & keluar
    val compactHide: String,
    val compactShow: String,
    val ramAvailable: String,
    val exitConfirm: String
)

val IndonesianStrings = Strings(
    appTitle = "AppController ",
    appTitleAccent = "Pro",
    shizukuConnected = "SHIZUKU TERHUBUNG",
    shizukuDisconnected = "SHIZUKU TERPUTUS",
    settings = "Pengaturan",
    vpnFilter = "FILTER VPN",
    vpnOff = "VPN MATI — filter jaringan tidak aktif",
    vpnOnActive = "VPN AKTIF — tunnel berjalan",
    vpnOnPreparing = "VPN AKTIF — menyiapkan tunnel...",
    memoryUsage = "PENGGUNAAN MEMORI",
    memoryShort = "RAM",
    ramUsedLabel = "Digunakan",
    ramTotalLabel = "Total",
    ramInUseLabel = "Terpakai",
    ramUserAppsLabel = "APLIKASI USER",
    ramCacheLabel = "CACHE",
    ramSystemLabel = "SISTEM",
    ramFreeLabel = "BEBAS",
    networkAccessAll = "Akses Jaringan All",
    killAll = "Hentikan Semua",
    filterAndSort = "Filter & Urutkan",
    userApps = "Aplikasi Pengguna",
    systemApps = "Aplikasi Sistem",
    info = "Info",
    tabApps = "Apps",
    tabSystem = "Sistem",
    tabAbout = "Tentang",
    version = "Versi 1.0.0",
    serviceStatus = "Status layanan",
    permissionsTitle = "Izin Aplikasi",
    permissionsSearch = "Cari izin",
    permissionsEmpty = "Tidak ada izin yang bisa dibaca untuk aplikasi ini.",
    permissionsNoMatch = "Tidak ada izin yang cocok.",
    permissionsRuntime = "Izin Runtime",
    permissionsAppOps = "Izin Lanjutan (AppOps)",
    legendChangeable = "bisa diubah",
    legendLocked = "terkunci",
    locked = "Terkunci",
    close = "Tutup",
    settingsTitle = "Pengaturan",
    languageSection = "Bahasa",
    themeSection = "Tema",
    themeDark = "Gelap",
    themeLight = "Terang",
    themeSystem = "Ikuti sistem",
    languageIndonesian = "Indonesia",
    languageEnglish = "English",
    openSystemAppInfo = "Buka info aplikasi di sistem",
    back = "Kembali",
    generalSection = "Umum",
    otherSection = "Lainnya",
    searchApps = "Cari aplikasi atau package",
    noMatchApps = "Tidak ada aplikasi yang cocok.",
    clearSearch = "Hapus pencarian",
    appInfoTitle = "Info Aplikasi",
    labelPackage = "Nama package",
    labelUid = "UID",
    labelVersion = "Versi",
    labelInstalled = "Tanggal instal",
    labelUpdated = "Terakhir diperbarui",
    labelSdk = "Target / Min SDK",
    labelType = "Jenis aplikasi",
    labelNetwork = "Akses jaringan",
    labelRunning = "Status",
    typeUserApp = "Aplikasi pengguna",
    typeSystemApp = "Aplikasi sistem",
    runningYes = "Sedang berjalan",
    runningNo = "Tidak berjalan",
    copyAction = "Salin",
    copiedAction = "Disalin",
    systemInfoAction = "Info sistem",
    activeLabel = "AKTIF",
    compactHide = "Versi Lite",
    compactShow = "Versi Max",
    ramAvailable = "Tersedia",
    exitConfirm = "Tekan kembali sekali lagi untuk keluar"
)

val EnglishStrings = Strings(
    appTitle = "AppController ",
    appTitleAccent = "Pro",
    shizukuConnected = "SHIZUKU CONNECTED",
    shizukuDisconnected = "SHIZUKU DISCONNECTED",
    settings = "Settings",
    vpnFilter = "VPN FILTER",
    vpnOff = "VPN OFF — network filter inactive",
    vpnOnActive = "VPN ON — tunnel running",
    vpnOnPreparing = "VPN ON — preparing tunnel...",
    memoryUsage = "MEMORY USAGE",
    memoryShort = "RAM",
    ramUsedLabel = "Used",
    ramTotalLabel = "Total",
    ramInUseLabel = "In use",
    ramUserAppsLabel = "USER APPS",
    ramCacheLabel = "CACHE",
    ramSystemLabel = "SYSTEM",
    ramFreeLabel = "FREE",
    networkAccessAll = "Network Access All",
    killAll = "Kill All",
    filterAndSort = "Filter & Sort",
    userApps = "User Apps",
    systemApps = "System Apps",
    info = "Info",
    tabApps = "Apps",
    tabSystem = "System",
    tabAbout = "About",
    version = "Version 1.0.0",
    serviceStatus = "Service status",
    permissionsTitle = "App Permissions",
    permissionsSearch = "Search permission",
    permissionsEmpty = "No permissions could be read for this app.",
    permissionsNoMatch = "No matching permission.",
    permissionsRuntime = "Runtime Permissions",
    permissionsAppOps = "Advanced (AppOps)",
    legendChangeable = "changeable",
    legendLocked = "locked",
    locked = "Locked",
    close = "Close",
    settingsTitle = "Settings",
    languageSection = "Language",
    themeSection = "Theme",
    themeDark = "Dark",
    themeLight = "Light",
    themeSystem = "Follow system",
    languageIndonesian = "Indonesia",
    languageEnglish = "English",
    openSystemAppInfo = "Open app info in system settings",
    back = "Back",
    generalSection = "General",
    otherSection = "Other",
    searchApps = "Search app or package",
    noMatchApps = "No matching app.",
    clearSearch = "Clear search",
    appInfoTitle = "App Info",
    labelPackage = "Package name",
    labelUid = "UID",
    labelVersion = "Version",
    labelInstalled = "Installed on",
    labelUpdated = "Last updated",
    labelSdk = "Target / Min SDK",
    labelType = "App type",
    labelNetwork = "Network access",
    labelRunning = "Status",
    typeUserApp = "User app",
    typeSystemApp = "System app",
    runningYes = "Running",
    runningNo = "Not running",
    copyAction = "Copy",
    copiedAction = "Copied",
    systemInfoAction = "System info",
    activeLabel = "ACTIVE",
    compactHide = "Versi Lite",
    compactShow = "Versi Max",
    ramAvailable = "Available",
    exitConfirm = "Press back again to exit"
)

fun stringsFor(language: AppLanguage): Strings =
    when (language) {
        AppLanguage.INDONESIAN -> IndonesianStrings
        AppLanguage.ENGLISH -> EnglishStrings
    }

val LocalStrings = staticCompositionLocalOf { IndonesianStrings }
